name: LwLogin
version: '1.2.0.2'
main: org.example_1.lwlogin_1.LwLogin_1
api-version: 1.20
commands:
  failsafediscard:
    usage: 用法:/failsafediscard [boolean] or /failsafediscard massage [boolean]
    aliases: fa
    description: 防误丢物品命令
